### ISSUE TITLE
Add DCO signoff checks

### ISSUE THREAD

**Issue by engelben** [ahege/openscenario.api.test#18]
I would suggest to also require DCO signoff on commits. This is something we have implemented for OSI and it provides a little bit more in the way of awareness of contributions. See [this issue](https://github.com/OpenSimulationInterface/open-simulation-interface/pull/397)

**Comment by ahege** [comment]
@engelben I added the contribution guidelines  [here](https://github.com/ahege/openscenario.api.test/blob/master/doc/howtocontribute.rst) and adopted the guidelines to the project.

Is there any way that we insure the sign-off when a branch is pushed or when a pull request is issued? Unfortunately, it seems I 've not access to all of the CI features of the OSI project.

**Comment by engelben** [comment]
@ahege just add [this app](https://probot.github.io/apps/dco/) to the repository

**Comment by ahege** [comment]
@engelben Installed and tested
