### ISSUE TITLE
Add licenses for example files and for xsd files.

### ISSUE THREAD

**Issue by ahege** [ahege/openscenario.api.test#2]
Still in question:

- OpenScenario.xsd
- All example files

Suggestion: Put them under Apache license.

**Comment by ahege** [comment]
@engelben: Do you have an idea how we can license the example files. I took for unit testing. Most of the license issues are clarified. 
Open: 
- ASAM example files,
- ASAM XSD file
- esmini example files. (I will clarify with Emil Knabe)

**Comment by engelben** [comment]
The XSD should be licensed under the original OSC license.

```
<!--
ASAM OpenSCENARIO V1.0.0

© by ASAM e.V., 2020

Description of dynamic content in driving simulations


Any use is limited to the scope described in the ASAM license terms. 
This file is distributable in accordance with the ASAM license terms. 
See www.asam.net/license.html for further details.
-->
```
The example files should be Apache 2.0 I think, i.e. as permissive as possible.

**Comment by ahege** [comment]
@engelben: Very good. I will add this header to every ASA example file:

**Comment by ahege** [comment]
@engelben: I will also add the license for the xsd to the NOTICE file.

**Comment by ahege** [comment]
See this [commit](https://github.com/ahege/openscenario.api.test/commit/80b163e818b2b9491104332d0509f7b7552026d3)
